---

- name: "Check if params file exists (if applicable)"
  stat:
    path: "{{ tmp_inv_dir }}{{ params }}"
  ignore_errors: yes
  register: params_result
  when:
  - params|trim != ''

- name: "Fail if params file doesn't exist (if applicable)"
  fail:
    msg: "{{ params }} - params file doesn't exist."
  when:
  - params|trim != ''
  - params_result.stat.exists == False

- name: "Determine location for the 'template'"
  vars:
    path: "{{ template }}"
  import_tasks: check-file-location.yml

- name: "Set 'template' values"
  set_fact:
    template: "{{ file_path }}"
    template_f_option: "{{ option_f }}"

- name: "Process template with params from vars"
  include_tasks: process-template-with-params-from-vars.yml
  when:
  - params|trim == ''
  - params_from_vars|trim != ''

- name: "Process template with params from a params file"
  include_tasks: process-template-with-params-from-file.yml
  when:
  - params|trim != ''
  - params_from_vars|trim == ''
