---

- name: "Determine location for the 'file'"
  vars:
    path: "{{ file }}"
  import_tasks: check-file-location.yml

- name: "Set 'file' values"
  set_fact:
    file: "{{ file_path }}"
    file_f_option: "{{ option_f }}"

- name: "{{ file_action | capitalize }} OpenShift objects based on static files for '{{ entry.object}} : {{ content.name | default(file | basename) }}'"
  command: >
    oc {{ file_action }} {{ target_namespace }} -f {{ file }} {{ (file_action == 'delete') | ternary(' --ignore-not-found', '') }}
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
