---

- name: "Set default values"
  set_fact:
    target_namespace: ''
    file: "{{ content.file | default('') }}"
    file_f_option: ''
    file_action: "{{ content.file_action | default(default_file_action) }}"
    template: "{{ content.template | default('') }}"
    template_f_option: ''
    template_action: "{{ content.template_action | default(default_template_action) }}"
    params: "{{ content.params | default('') }}"
    params_from_vars: "{{ content.params_from_vars | default('') }}"
    process_local: ''

- name: "Set file_action and template_action to delete when in deprovision mode"
  set_fact:
    file_action: "delete"
    template_action: "delete"
  when:
  - not provision|bool

- name: "Set the target namespace option if supplied"
  set_fact:
    target_namespace: "-n {{ content.namespace }}"
  when:
  - content.namespace is defined
  - content.namespace|trim != ''

- name: "Include any pre-processing role(s) before applying file and/or template"
  include_tasks: pre-post-step.yml
  with_items:
  - "{{ content.pre_steps | default('') }}"
  loop_control:
    loop_var: step

- name: "Process Template (if applicable)"
  include_tasks: process-template.yml
  when:
  - template|trim != ''
  - params|trim != '' or params_from_vars|trim != ''

- name: "Process File (if applicable)"
  include_tasks: process-file.yml
  when:
  - file|trim != ''

- name: "Include any post-processing role(s) after applying file and/or template"
  include_tasks: pre-post-step.yml
  with_items:
  - "{{ content.post_steps | default('') }}"
  loop_control:
    loop_var: step
