---
#TODO: CHANGE THIS SO IT ENUMERATES THE VARS INTO THE COMMANDLINE

- name: "{{ template_action | capitalize }} OpenShift objects based on template with params for '{{ entry.object}} : {{ content.name | default(template | basename) }}'"
  shell: >
    oc process \
      {{ process_local }} \
      {{ template_f_option }} {{ template }} \
      {{ target_namespace }} \
      --param-file={{ tmp_inv_dir }}{{ content.params }} | \
    oc {{ template_action }} {{ target_namespace }} -f - {{ (template_action == 'delete') | ternary(' --ignore-not-found', '') }}
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
  when:
  - template|trim != ''
  - params|trim != ''
  - not params_result.stat.isdir

- name: "{{ template_action | capitalize }} OpenShift objects based on template with params for '{{ entry.object}} : {{ content.name | default(template | basename) }}'"
  shell: >
    oc process \
      {{ process_local }} \
      {{ template_f_option }} {{ template }} \
      {{ target_namespace }} \
      --param-file={{ item }} | \
    oc {{ template_action }} {{ target_namespace }} -f - {{ (template_action == 'delete') | ternary(' --ignore-not-found', '') }}
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
  with_fileglob:
  - "{{ tmp_inv_dir }}{{ content.params }}/*"
  when:
  - template|trim != ''
  - params|trim != ''
  - params_result.stat.isdir
